### PR TITLE
Create Complements

### PR DESCRIPTION
**Pull request by klutz2121**
I've created 1's complement in C programme. Thanks.

### CODE REVIEW

**Comment by Kakashiutano** [comment]
Hello! Thanks for the codes. It was good but I think it will be much more convenient if you add a condition when the user puts number other than 0 and 1 it should terminates or restarts the program noting that you've put the wrong input value. Thanks.

**Comment by klutz2121** [comment]
Oh, I shall fix it then and leave it to me.

**Comment by Kakashiutano** [comment]
Thanks!

**Comment by klutz2121** [comment]
By the way I have done the change. Test it yourself. Cheers

**Comment by Kakashiutano** [comment]
One more error, It shows the "Invalid input" even I put the number as binary. From my last code, I checked the condition every time I take one character or input. Checkout my code in the Binary Complement.c file (though it's still not efficient enough). By the way thanks for the effort. I appreciate it.

**Comment by klutz2121** [comment]
There you go a new one and hope it is working fine and thanks for your comments.

**Comment by Kakashiutano** [comment]
This is it! Thank you so much for the efforts. Again, I appreciate it. I'll merge it

**Pull request merged**
